### 🏠 Welcome Route
GET https://contacts-b.onrender.com/

### 📄 Get All Contacts
GET https://contacts-b.onrender.com/contacts

### 🔍 Get Contact by ID
GET https://contacts-b.onrender.com/contacts/68304071f8c30f9a916eb5cd

### ➕ Add New Contact
POST https://contacts-b.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "James",
  "lastName": "Doe",
  "email": "example@gmail.com",
  "favoriteColor": "blue",
  "birthday": "1990-01-01"
}

### ✏️ Update Contact
PUT https://contacts-b.onrender.com/contacts/68304071f8c30f9a916eb5cd
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "real@email.com"
}

### ❌ Delete Contact
DELETE https://contacts-b.onrender.com/contacts/682ec6ccca8513c06bda01c7
