### 🏠 Welcome Route
GET http://localhost:8080/

### 📄 Get All Contacts
GET http://localhost:8080/contacts

### 🔍 Get Contact by ID
GET http://localhost:8080/contacts/123

### ➕ Add New Contact
POST http://localhost:8080/contacts
Content-Type: application/json

### ✏️ Update Contact
PUT http://localhost:8080/contacts/123
Content-Type: application/json


### ❌ Delete Contact
DELETE http://localhost:8080/contacts/123
